#### Question 1

Disply the following sentence in bold font face <br>
"This is fisrt lab of Applied Computational Statics"

In [1]:
from IPython.display import Markdown

Markdown("**This is first lab of Applied Computational Statics**")


**This is first lab of Applied Computational Statics**

#### Question 2

Recreate the following bullet points in  Jupyter notebook markdown cell:
markdown cell : markdown <br>
code cell: Python code <br>
Subject: Statistics 

In [2]:
from IPython.display import Markdown

md_text = """
- **Markdown cell:** markdown  
- **Code cell:** Python code  
- **Subject:** Statistics  
"""

display(Markdown(md_text))



- **Markdown cell:** markdown  
- **Code cell:** Python code  
- **Subject:** Statistics  


#### Question 3

**Run the following code in two different Jupyter notebook cells. Run one cell as a code cell. Run the other cell as a Markdown cell. Why is the output different?**

#### Question 4

**Use *float()* to create a number from a string like '12.34'. Make sure the result is really a number!**

In [3]:

num = float('12.34')
print(num, "is of type:", type(num))

12.34 is of type: <class 'float'>


#### Question 5

Write a simple Python program that displays the following **powers of 2**, one per line: $$2^1, 2^2, 2^3, 2^4, 2^5, 2^6, 2^7, 2^8$$

In [4]:

for i in range(1, 9):
    print(f"2^{i} = {2**i}")


2^1 = 2
2^2 = 4
2^3 = 8
2^4 = 16
2^5 = 32
2^6 = 64
2^7 = 128
2^8 = 256


#### Question 6

**Write a Python program that allows the user to enter any integer value, and displays the value of 2 raised to that power. Your program should function as shown below.**

What power of two? 10

Two to the power of 10 is 1024

In [5]:

n = int(input("enter no"))
result = 2 ** n
print(f"Two to the power of {n} is {result}")


ValueError: invalid literal for int() with base 10: ''

#### Question 7

**Write a python program that prompt the user to enter a list of numbers and returns the index of the smallest element in a list of integers.**

**If the number of occurrence of smallest element is greater than 1, return the smallest index.**

In [ ]:

numbers = list(map(int, input("Enter a list of numbers separated by space: ").split()))
smallest = min(numbers)
index_of_smallest = numbers.index(smallest)
print(f"The index of the smallest element ({smallest}) is {index_of_smallest}")


The index of the smallest element (22) is 0


#### Question 8

**Losing Your Head over Chess**

The game of chess is generally believed to have been invented in India in the sixth century for a ruling king by one of his subjects. The king was supposedly very delighted with the game and asked the subject what he wanted in return. The subject, being clever, asked for one grain of wheat on the first square, two grains of wheat on the second square, four grains of wheat on the third square, and so forth, doubling the amount on each next square. The king thought that this was a modest reward for such an invention. However, the total amount of wheat would have been more than 1,000 times the current world production.

**Develop and test a Python program that calculates how much wheat this would be in pounds, using the fact that a grain of wheat weighs approximately $1/7,000$ of a pound.**

In [ ]:

grains_per_pound = 7000 
total_grains = 0
for i in range(64):
    total_grains += 2 ** i  
tp = total_grains / grains_per_pound
print(tp)


2635249153387079.0


#### Question 9

**Write a Python program that prompts the user for two floating-point values and displays the result of the first number divided by the second, in integer only.**

In [ ]:

num1 = float(input("first floating-point value: "))
num2 = float(input("second floating-point value: "))
result = int(num1 / num2)
print(f"The result of {num1} divided by {num2} is {result} ")


The result of 343.3234 divided by 344.233 is 0 


#### Question 10

**Use NumPy to generate a random number between 0 and 1**

In [ ]:
import numpy as np
random_number = np.random.rand()
print(f"Random no between 0 and 1: {random_number}")


Random number between 0 and 1: 0.20024377245208846


#### Question 11

**Create an array of 20 linearly spaced points between 0 and 1**

In [ ]:
import numpy as np

array = np.linspace(0, 1, 20)

print(array)


Array of 20 linearly spaced points between 0 and 1:
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


#### Question 12

**Create following array using numpy and siply sum of rows and sum of coloumns** <br>
[[ 1,  2,  3,  4,  5],<br>
 [ 6,  7,  8,  9, 10], <br>
 [11, 12, 13, 14, 15], <br>
 [16, 17, 18, 19, 20], <br>
 [21, 22, 23, 24, 25]]

**Evaluate each of the following Python expressions first by hand and then verify using jupyter notebook. Assume any value of $(d1,d2,d3)$** <br>
<b>1.</b>	$(d1 + d2 + d3) / 3$ <br>
<b>2.</b>	$d1 + d2 + (d3 / 3)$<br>
<b>3.</b>	$3 * (d1 + d2) * (d1 - d3)$

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20],
                [21, 22, 23, 24, 25]])

sum_rows = np.sum(arr, axis=1)

sum_columns = np.sum(arr, axis=0)

print("Array:")
print(arr)
print("\nSum of rows:")
print(sum_rows)
print("\nSum of columns:")
print(sum_columns)


Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sum of rows:
[ 15  40  65  90 115]

Sum of columns:
[55 60 65 70 75]
